services:
  bookmanagement.api:
    image: ${DOCKER_REGISTRY-}bookmanagementapi
    build:
      context: .
      dockerfile: BookManagement.API/Dockerfile
    depends_on:
     - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "Adm1n23%"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: